"""
The sponsorship predicates, in one place, as SQL over a description column.

They used to live in dbt_signal/models/staging/stg_jobs.sql, which is the wrong
home for two reasons.

First, they recomputed on every run from description_raw, which meant the text
could never leave the serving database. That text is 208 MB of a 512 MB budget and
has already done its only other jobs - technology extraction and LLM scoring.

Second, they were the source of three separate cross-engine bugs. Postgres
regexp_like searches anywhere while Snowflake's matches the whole string, so nine
patterns needed .* wrapping; Snowflake's . stops at a line break without the s
flag, so multi-line descriptions lost every match below the first paragraph; and
adjacent quoted strings concatenate on Postgres but are a syntax error on
Snowflake. Computing these once at load time, in Postgres, and storing the answer
as two booleans removes every one of those hazards from the portable layer. The
models downstream now read a boolean and contain no regex at all.

Evaluated once per posting when it is loaded, rather than once per posting per dbt
run, which is also simply less work.
"""

from __future__ import annotations

# Each entry is one alternative. A posting refuses sponsorship if any matches.
#
# Written against Postgres deliberately: this runs only here, on the way in, so it
# may use whatever Postgres offers. That is the point of moving it out of the
# cross-engine layer.
REFUSES = [
    r"(will not|does not|do not|cannot|can not|are not able to|unable to|"
    r"not be able to|not offer|not provide)[^.]{0,80}sponsor",
    r"sponsorship[^.]{0,60}(is not|not available|will not be|cannot be|"
    r"is unavailable)",
    r"does not now or in the future require sponsorship",
    r"do not apply[^.]{0,80}sponsor",
    r"without the need for[^.]{0,40}sponsor",
]

# Deliberately narrow. This describes a posting; it never cancels a refusal -
# apply_queue gives the refusal precedence, because General Motors has 1,141
# filings and still states it does not sponsor for 33 specific roles.
OFFERS = [
    r"(we|company) (do|does|will|can|are able to|are willing to|are happy to)"
    r"[^.]{0,20}sponsor",
    r"sponsorship (is|will be) available",
    r"will consider sponsor",
]


def predicate(column: str, patterns: list[str]) -> str:
    """An OR of case-insensitive matches against `column`."""
    # Dollar-quoted, so a pattern containing a single quote or a backslash needs
    # no escaping and cannot end the literal early. The patterns are constants in
    # this file and never user input.
    parts = [f"{column} ~* $q${pattern}$q$" for pattern in patterns]
    return "(" + " OR ".join(parts) + ")"


def refuses_sql(column: str = "description_raw") -> str:
    return predicate(column, REFUSES)


def offers_sql(column: str = "description_raw") -> str:
    return predicate(column, OFFERS)


# The CI fixture needs the same verdicts, and CI does not run the loader. Rather
# than a second, simplified copy of the patterns in tests/fixtures/seed_ci.sql -
# which would quietly become a lie the first time a pattern changed here - the
# fixture carries a generated block and a test asserts it still matches this.
FIXTURE_BEGIN = "-- BEGIN generated by storage/sponsorship_text.py"
FIXTURE_END = "-- END generated"


def fixture_update(table: str = "raw_postings") -> str:
    """The UPDATE that applies both verdicts, for the CI fixture."""
    return (
        f"{FIXTURE_BEGIN}\n"
        f"UPDATE {table} SET\n"
        f"    refuses_sponsorship = {refuses_sql()},\n"
        f"    offers_sponsorship  = {offers_sql()}\n"
        f"WHERE description_raw IS NOT NULL;\n"
        f"{FIXTURE_END}"
    )


if __name__ == "__main__":  # pragma: no cover - a convenience, not a code path
    print(fixture_update())
